### ISSUE TITLE
Fix things that stopped working after py3 updates

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/nexpose-client-python#32]
The following things in run_demo.py are not working after the py3 updates:

- [x] DemonstrateVulnerabilityAPI() (fixed in #31)
- [x] DemonstrateBackupAPI()
- [x] DemonstrateCriteriaAPI()
- [x] DemonstrateSharedCredentialsAPI()
- [x] DemonstrateAssetFilterAPI()
-  ~~DemonstrateDiscoveryConnectionAPI()~~
- [x] DemonstrateUserAPI()

**Comment by ghost** [comment]
@gschneider-r7 , that should be all of the above covered with 
PRs#34,35,36. I don't think `DemonstrateDiscoveryConnectionAPI()` is broke as the error in the nsc.log file indicates a connection problem rather than an actual problem with the python client.
`2017-10-07T19:14:45 [WARN] Failed while connecting to discovery center.`
