### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/nexpose-client-python#4]
Refactor the project to work in both Python2 and Python3

https://docs.python.org/3/howto/pyporting.html

http://python-future.org/compatible_idioms.html

**Comment by dhaynespls** [comment]
Are you looking for contributors? I've worked on py2/3 compatibility on a handful of projects and would be happy to help. Since there's tests already this should be relatively simple to take care of and ensure the library works.

another link: http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html

**Comment by gschneider-r7** [comment]
Hi @dhaynespls we'd be happy to have new contributors help out with this project. 😃

**Comment by dhaynespls** [comment]
Cool, I'm looking into it here: 

https://github.com/dhaynespls/nexpose-client-python/tree/4-py3-backwards-compat

I'll open a PR when it's good to go (passing all the tests).
